<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JDBMapLiteDao [
	<!ELEMENT JDBMapLiteDao (sql*)>
	<!ELEMENT sql (default,dataSource*)>
	<!ATTLIST sql id ID #REQUIRED type CDATA #IMPLIED>
	<!ELEMENT default (#PCDATA)>
	<!ELEMENT dataSource (#PCDATA)>
	<!ATTLIST dataSource id CDATA #REQUIRED>
]>
<!-- Generated by jDBMapLite-Generator -->
<JDBMapLiteDao>
	<sql id="getUser" type="client.User">
		<default><![CDATA[select user_key, user_name, user_id, created_at, created_by, is_archived_flag from user where condition = 'your condition']]></default>
	</sql>
	<sql id="getUsers" type="client.User">
		<default><![CDATA[select user_key, user_name, user_id, created_at, created_by, is_archived_flag from user]]></default>
	</sql>
	<sql id="updateUser">
		<default><![CDATA[update user set update_data = 'your data' where condition = 'your condition']]></default>
	</sql>
	<sql id="createUser" type="client.User">
		<default><![CDATA[insert into user (user_key, user_name, user_id, created_at, created_by, is_archived_flag) values ('your data')]]></default>
	</sql>
</JDBMapLiteDao>