<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JDBMapLiteManager [
	<!ELEMENT JDBMapLiteManager (dataSource+,connectionPool*)>
	<!ATTLIST JDBMapLiteManager dataSourceId CDATA #IMPLIED connectionPoolId (c3p0|dbcp|jndi|proxool) #IMPLIED>
	<!ELEMENT dataSource (property*)>
	<!ATTLIST dataSource id CDATA #IMPLIED>
	<!ELEMENT connectionPool (property*)>
	<!ATTLIST connectionPool id CDATA #IMPLIED>
	<!ELEMENT property (#PCDATA)>
	<!ATTLIST property name CDATA #REQUIRED>
]>
<!-- Generated by jDBMapLite-Generator -->
<JDBMapLiteManager dataSourceId="sqlite" connectionPoolId="c3p0">
	<dataSource id="sqlite">
		<property name="driver">org.sqlite.JDBC</property>
		<property name="url">jdbc:sqlite:test.db</property>
		<property name="user"></property>
		<property name="password"></property>
	</dataSource>
	<connectionPool id="c3p0">
		<property name="minPoolSize">10</property>
		<property name="maxPoolSize">20</property>
	</connectionPool>
</JDBMapLiteManager>